### ISSUE TITLE
useRef与vue的更新机制不一样

### ISSUE THREAD

**Issue by agileago** [veactjs/veact#6]
useRef这块是不是watch得时候应该是`deep`的

比如在vue中： 

`ref`传递一个对象或者数组，对其进行操作是会触发界面更新的

<img width="737" alt="image" src="https://github.com/veactjs/veact/assets/11799110/f6385865-ef3d-42f8-b7ec-6109b093568d">

但是在`veact`中就不会

<img width="745" alt="image" src="https://github.com/veactjs/veact/assets/11799110/05142c0e-1afa-4db6-b567-49ce061b5477">

**Comment by surmon-china** [comment]
Fixed in [v1.0.0-beta.1](https://github.com/veactjs/veact/blob/v1.0.0-beta.1/CHANGELOG.md#v100-beta1-2024-08-12).
